### ISSUE TITLE
Update for jhipster version 6.0.0

### ISSUE THREAD

**Issue by The-Crocop** [cbornet/generator-jhipster-grpc#25]
The generator should be updated for the new jhipster version 6.x which was released in the past days

**Comment by cbornet** [comment]
Indeed. I think it's even broken for some 5.x versions. I'll try to find time to update it.
Help through PRs is very welcome of course !

**Comment by cbornet** [comment]
FYI version 0.16.0 was just released which works for JH 5.0 to 5.7.

**Comment by cbornet** [comment]
@The-Crocop I just released v0.21.2 of the module which should work fine with the latest Jhipster version. Can you test if it works for you ?
